[project]
name = "lentezinha"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ivan Ramos Pagnossin", email = "puchacz.23@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13.4",
]

[build-system]
requires = ["uv_build>=0.11.32,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
